language: php

os: linux
dist: xenial

services:
  - mysql
  - postgresql
  - docker

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

jobs:
  include:
    - php: 7.3
      env:
        - MOODLE_BRANCH=master
        - DB=mysqli

    - php: 7.4
      env:
        - MOODLE_BRANCH=MOODLE_39_STABLE
        - DB=pgsql

    - php: 7.3
      env:
        - MOODLE_BRANCH=MOODLE_38_STABLE
        - DB=pgsql
        - CHECK_GRUNT=yes

    - php: 7.2
      env:
        - MOODLE_BRANCH=MOODLE_37_STABLE
        - DB=mysqli

    - php: 7.1
      env:
        - MOODLE_BRANCH=MOODLE_36_STABLE
        - DB=pgsql
        - NODE=8.9

before_install:
  - phpenv config-rm xdebug.ini

  - if [ -z $CHECK_GRUNT ]; then
      export CHECK_GRUNT=no;
    fi

  - if [ -z $NODE ]; then
      export NODE=14;
    fi
  - nvm install $NODE
  - nvm use $NODE

  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - moodle-plugin-ci install

  # Work-around to get Behat/Chrome to work, thanks to https://travis-ci.org/github/kabalin/moodle-qtype_stack/jobs/661027012/config
  - export MOODLE_START_BEHAT_SERVERS=NO
  - docker run -d -p 4444:4444 --net=host -v /dev/shm:/dev/shm -v $HOME/build/moodle:$HOME/build/moodle selenium/standalone-chrome:3
  - php -S localhost:8000 -t $HOME/build/moodle > /dev/null 2>&1 &

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd || true
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker || true
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache || true
  - moodle-plugin-ci grunt || [ "$CHECK_GRUNT" = 'no' ]
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat --profile chrome
